export const MenuListar = () => {
  return (
    <>
      <h1>Campeones de League of Legends</h1>
      <ul>
        <li>Aatrox</li>
        <li>Ahri</li>
        <li>Akali</li>
        <li>Alistar</li>
        <li>Amumu</li>
        <li>Anivia</li>
        <li>Annie</li>
        <li>Aphelios</li>
        <li>Ashe</li>
        <li>Aurelion Sol</li>
        <li>Azir</li>
        <li>Bard</li>
        <li>Blitzcrank</li>
        <li>Brand</li>
        <li>Braum</li>
        <li>Caitlyn</li>
        <li>Camille</li>
        <li>Carma</li>
        <li>Chogath</li>
        <li>Clid</li>
        <li>Dr. Mundo</li>
        <li>Elise</li>
        <li>Ekko</li>
        <li>Fiddlesticks</li>
        <li>Fiora</li>
        <li>Fizz</li>
        <li>Galio</li>
        <li>Garen</li>
        <li>Gnar</li>
        <li>Gragas</li>
        <li>Graves</li>
        <li>Gwen</li>
        <li>Heimerdinger</li>
        <li>Illaoi</li>
        <li>Irelia</li>
        <li>Janna</li>
        <li>Jarvan IV</li>
        <li>Jax</li>
        <li>Jhin</li>
        <li>Jinx</li>
        <li>Kai'Sa</li>
        <li>Karma</li>
        <li>Karthus</li>
        <li>Kassadin</li>
        <li>Katarina</li>
        <li>Kennen</li>
        <li>Kled</li>
        <li>Kog'Maw</li>
        <li>LeBlanc</li>
        <li>Lee Sin</li>
        <li>Leona</li>
        <li>Lillia</li>
        <li>Lissandra</li>
        <li>Lucian</li>
        <li>Lux</li>
        <li>Malphite</li>
        <li>Malzahar</li>
        <li>Maokai</li>
        <li>Miss Fortune</li>
        <li>Mordekaiser</li>
        <li>Morgana</li>
        <li>Nami</li>
        <li>Nasus</li>
        <li>Nautilus</li>
        <li>Neeko</li>
        <li>Nidalee</li>
        <li>Nocturne</li>
        <li>Nunu y Willump</li>
        <li>Olaf</li>
        <li>Orianna</li>
        <li>Ornn</li>
        <li>Pantheon</li>
        <li>Poppy</li>
        <li>Rakan</li>
        <li>Ramus</li>
        <li>Rek'Sai</li>
        <li>Rell</li>
        <li>Renekton</li>
        <li>Riven</li>
        <li>Rumble</li>
        <li>Ryze</li>
        <li>Samira</li>
        <li>Sejuani</li>
        <li>Senna</li>
        <li>Seraphine</li>
        <li>Sett</li>
        <li>Shaco</li>
        <li>Shen</li>
        <li>Shyvana</li>
        <li>Sion</li>
        <li>Sivir</li>
        <li>Sona</li>
        <li>Soraka</li>
        <li>Swain</li>
        <li>Syndra</li>
        <li>Tahm Kench</li>
        <li>Taliyah</li>
        <li>Talon</li>
        <li>Taric</li>
        <li>Teemo</li>
        <li>Thresh</li>
        <li>Twisted Fate</li>
        <li>Udyr</li>
        <li>Vayne</li>
        <li>Veigar</li>
        <li>Vel'Koz</li>
        <li>Vex</li>
        <li>Viego</li>
        <li>Viktor</li>
        <li>Vladimir</li>
        <li>Volibear</li>
        <li>Warwick</li>
        <li>Wukong</li>
        <li>Yasuo</li>
        <li>Yone</li>
        <li>Yuumi</li>
        <li>Zac</li>
        <li>Zed</li>
        <li>Zeri</li>
        <li>Ziggs</li>
        <li>Zilean</li>
        <li>Zyra</li>
      </ul>
    </>
  );
};
